BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES;

CREATE TABLE CIDADES (
    CIDADES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADES_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS(
    PESSOA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PESSOA_NOME TEXT NOT NULL,
    PESSOA_IDADE INTEGER,
    PESSOA_CIDADES_ID INTEGER NOT NULL
);

INSERT INTO CIDADES(CIDADES_NOME)
    VALUES
    ('Campo Grande'),
    ('Blumenau'),
    ('Florianopolis'),
    ('Lages');

INSERT INTO PESSOAS(PESSOA_NOME,PESSOA_IDADE,PESSOA_CIDADES_ID)
    VALUES
    ('Adriano',47,1),
    ('Rodolfo',47,3),
    ('Carlos',80,2),
    ('Lucas',20,4),
    ('Pedro',18,3),
    ('Maria',18,2),
    ('Maria',22,4);

COMMIT;

SELECT * FROM CIDADES;
SELECT * FROM PESSOAS;