--SELECT * FROM PESSOAS;
--SELECT * FROM CIDADES;

--SELECT PESSOA_NOME,PESSOA_IDADE FROM PESSOAS;

--SELECT DISTINCT (PESSOA_NOME) FROM PESSOAS;

--SELECT * FROM PESSOAS WHERE PESSOA_IDADE IN (14,20);

--SELECT * FROM PESSOAS WHERE PESSOA_NOME LIKE '%Maria%';

--SELECT * FROM PESSOAS WHERE PESSOA_NOME LIKE '%Maria%' AND PESSOA_IDADE = 18;

--SELECT * FROM PESSOAS WHERE PESSOA_NOME LIKE '%Maria%' OR PESSOA_IDADE = 18;

--SELECT * FROM PESSOAS WHERE PESSOA_IDADE BETWEEN 45 AND 50;

--SELECT PESSOA_IDADE,PESSOA_NOME FROM PESSOAS ORDER BY PESSOA_IDADE;

--SELECT PESSOA_IDADE,PESSOA_NOME FROM PESSOAS ORDER BY PESSOA_IDADE DESC;

--SELECT PESSOA_IDADE,PESSOA_NOME FROM PESSOAS ORDER BY PESSOA_IDADE,PESSOA_NOME;

--SELECT avg(PESSOA_IDADE) FROM PESSOAS;

--SELECT min(PESSOA_IDADE) FROM PESSOAS;

--SELECT max(PESSOA_IDADE) FROM PESSOAS;

--SELECT sum(PESSOA_IDADE) FROM PESSOAS;

--SELECT count(*) FROM PESSOAS;

SELECT PESSOA_IDADE, count(PESSOA_NOME) FROM PESSOAS GROUP BY PESSOA_IDADE;

--SELECT
    --CIDADES.CIDADES_NOME,
    --PESSOAS.PESSOA_NOME,
    --PESSOAS.PESSOA_IDADE
--FROM 
    --PESSOAS,CIDADES
--WHERE
    --PESSOAS.PESSOA_CIDADES_ID = CIDADES.CIDADES_ID;

/* 
Resultado:
Campo Grande|Adriano|47
Florianopolis|Rodolfo|47
Blumenau|Carlos|80
Lages|Lucas|20
Florianopolis|Pedro|18
Blumenau|Maria|18
Lages|Maria|22 */

