


--RESULTS_SETS RETORNA PRATELEIRAS E NOME DO LOCAL
SELECT PRATELEIRA_NOME, PRATELEIRA_LOCAL FROM PRATELEIRAS;


--RESULTS_SETS PRODUTOS ORDENADOS POR PRATELEIRAS
SELECT * FROM PRODUTOS ORDER BY PRODUTO_PRATELEIRAS_ID;


--RESULTS_SETS 1 CUPOM FISCAL COMPLETO, LISTANDO CAMPOS DE DIVERSAS TABELAS
SELECT 
    NOTA_DATA,
    NOTA_NUM,
    PRODUTO_NOME,
    PRODUTO_VALORUNIT
        
FROM ITENSNOTA, NOTAS, PRODUTOS

WHERE ITENSNOTA.ITEMNOTA_SEQ = NOTAS.NOTA_NUM 
AND ITENSNOTA.ITEMNOTA_PRODUTOS_ID = PRODUTOS.PRODUTO_ID
AND NOTAS.NOTA_NUM = 1010;


--- RESULTS_SETS CLIENTES (TODOS OS CAMPOS)
SELECT * FROM CLIENTES;


--- RESULTS_SETS CLIENTES (LISTANDO SOMENTE CAMPO NOME)
SELECT CLIENTE_NOME FROM CLIENTES;


--- RESULTS_SETS ATENDENTES (TODOS OS CAMPOS)
SELECT * FROM ATENDENTES;


--- RESULTS_SETS ATENDENTES (LISTANDO SOMENTE CAMPO NOME)
SELECT ATENDENTE_NOME FROM ATENDENTES;







