BEGIN TRANSACTION;
DROP TABLE IF EXISTS PESSOAS;
CREATE TABLE PESSOAS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,    
    CPF         TEXT    NOT NULL, 
    NOME        TEXT    NOT NULL,
    IDADE       INT     NOT NULL,
    ENDERECO    CHAR(50),
    SALARIO     REAL 
);
INSERT INTO PESSOAS (CPF,NOME,IDADE,ENDERECO,SALARIO)
    VALUES
    ('123.456.789-99','Karina',45,'Rua Rosario, 478','100000.00'),
    ('333.222.789-99','ADRIANO',47,'Rua Flamboyants,50', '100000.00');

COMMIT;
SELECT * FROM PESSOAS;